

export const theme = {
    white: '#FFFFFF',
    primaryColor: '#3A5BA9',
    onPrimaryColor: '#FFFFFF',
    primaryContainerColor: '#DAE2FF',
    onPrimaryContainerColor: '#001847',
    secondaryColor: '#00696B',
    onSecondaryColor: 'FFFFFF',
    secondaryContainerColor: '#6FF6F8',
    onSecondaryContainerColor: '#002020',
    tertiaryColor: '#5555A9',
    onTertiaryColor: 'FFFFFF',
    tertiaryContainerColor: '#E2DFFF',
    onTertiaryContainerColor: '#00210C',
    errorColor: '#BA1A1A',
    onErrorColor: 'FFFFFF',
    errorContainerColor: '#FFDAD6',
    onErrorContainerColor: '#410002',
    backgroundColor: '#FEFBFF',
    onBackgroundColor: '#1B1B1F',
    surfaceColor: '#FEFBFF',
    onSurfaceColor: '#1B1B1F',
};
